# fly.toml file generated for innd-ha on 2023-04-04T13:44:35-07:00

app = "innd-ha"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lax"
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250
